name: Build snap package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: snapcore/action-build@v1
      id: snapcraft

    - name: Install snap
      run: |
        sudo snap set system experimental.user-daemons=true
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}

    - uses: actions/upload-artifact@v4
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
