#!/usr/bin/env bash
set -eo pipefail
mkdir "$SNAP_DATA"/flexget
if [ ! -f "$SNAP_DATA/flexget/config.yml" ]; then
  cat <<EOT > "$SNAP_DATA"/flexget/config.yml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes
tasks: {}
EOT
fi
